#!/bin/sh

uci set luci.main.lang='zh_cn'
uci set luci.main.mediaurlbase='/luci-static/bootstrap-light'
uci commit luci

uci set system.@system[0].timezone='CST-8'
uci set system.@system[0].zonename='Asia/Shanghai'
uci commit system

uci set fstab.@global[0].anon_mount=1
uci commit fstab

uci set dhcp.lan.start='6'
uci set dhcp.lan.limit='50'
uci set dhcp.lan.leasetime='24h'
uci set dhcp.lan.force='1'
uci set dhcp.lan.ra_flags='none'
uci delete dhcp.lan.dhcpv6
uci commit dhcp

sed -i 's/root::0:0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow

sed -i 's/DISTRIB_DESCRIPTION='"'"'/DISTRIB_DESCRIPTION='"'"'Ungelivable /' /etc/openwrt_release

sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

echo 'hsts=0' > /root/.wgetrc

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

exit 0
